import type { ResolvedDocsConfig } from "./resolve.js";
import { convertSidebar } from "./sidebar.js";

export interface GeneratedFiles {
    /** Content for .trickfire/docusaurus.config.js */
    config: string;
    /** Content for .trickfire/sidebars.js, or null to use autogenerated sidebar. */
    sidebars: string | null;
}

export function generateFiles(config: ResolvedDocsConfig): GeneratedFiles {
    const navItems = config.social.map((s) => ({
        href: s.href,
        label: s.label,
        position: "right",
    }));

    const docsOptions: Record<string, unknown> = {
        path: "docs",
        routeBasePath: "/",
    };

    let sidebars: string | null = null;

    if (config.sidebar) {
        const converted = convertSidebar(config.sidebar);
        docsOptions.sidebarPath = ".trickfire/sidebars.js";
        sidebars = `// @generated by trickfire-docs — do not edit\nexport default { sidebar: ${JSON.stringify(converted, null, 2)} };\n`;
    }

    const cfg = {
        title: config.name,
        tagline: config.description,
        url: "http://localhost:3000",
        baseUrl: "/",
        onBrokenLinks: "warn",
        onBrokenMarkdownLinks: "warn",
        themeConfig: {
            colorMode: {
                defaultMode: "dark",
                disableSwitch: true,
                respectPrefersColorScheme: false,
            },
            navbar: {
                title: config.name,
                items: navItems,
            },
            footer: {
                style: "dark",
                copyright: "TrickFire Robotics",
            },
        },
        presets: [
            [
                "@docusaurus/preset-classic",
                {
                    docs: docsOptions,
                    blog: false,
                    pages: false,
                    theme: { customCss: [".trickfire/custom.css"] },
                },
            ],
        ],
    };

    return {
        config: `// @generated by trickfire-docs — do not edit\nexport default ${JSON.stringify(cfg, null, 2)};\n`,
        sidebars,
    };
}
