import path from "node:path";
import { createRequire } from "node:module";
import type { ResolvedDocsConfig } from "./resolve.js";
import { convertSidebar } from "./sidebar.js";

// Resolve preset/plugin paths from the trickfire-docs package context so that
// the generated config works in member repos regardless of their node_modules
// layout — absolute paths bypass Docusaurus's site-dir module resolver.
const _require = createRequire(import.meta.url);
const PRESET_CLASSIC_PATH = path.dirname(
    _require.resolve("@docusaurus/preset-classic/package.json")
);

export interface GeneratedFiles {
    /** Content for .trickfire/docusaurus.config.js */
    config: string;
    /** Content for .trickfire/sidebars.js, or null to use autogenerated sidebar. */
    sidebars: string | null;
}

export function generateFiles(config: ResolvedDocsConfig, projectRoot: string): GeneratedFiles {
    const navItems = config.social.map((s) => ({
        href: s.href,
        label: s.label,
        position: "right",
    }));

    // Docusaurus treats siteDir (.trickfire-docs/) as the site root.
    // Every file reference must be absolute to avoid resolving against the wrong base.
    const docsDir = path.resolve(projectRoot, "docs");
    const trickfireDir = path.resolve(projectRoot, ".trickfire-docs");
    const customCssPath = path.join(trickfireDir, "custom.css");
    const sidebarsPath = path.join(trickfireDir, "sidebars.js");

    const docsOptions: Record<string, unknown> = {
        path: docsDir,
        routeBasePath: "/",
    };

    let sidebars: string | null = null;

    if (config.sidebar) {
        const converted = convertSidebar(config.sidebar);
        docsOptions.sidebarPath = sidebarsPath;
        sidebars = `// @generated by trickfire-docs — do not edit\nexport default { sidebar: ${JSON.stringify(converted, null, 2)} };\n`;
    }

    const cfg = {
        title: config.name,
        tagline: config.description,
        url: "http://localhost:3000",
        baseUrl: "/",
        onBrokenLinks: "warn",
        onBrokenMarkdownLinks: "warn",
        staticDirectories: [path.resolve(projectRoot, "public")],
        themeConfig: {
            colorMode: {
                defaultMode: "dark",
                disableSwitch: true,
                respectPrefersColorScheme: false,
            },
            navbar: {
                title: config.name,
                items: navItems,
            },
            footer: {
                style: "dark",
                copyright: "TrickFire Robotics",
            },
        },
        presets: [
            [
                PRESET_CLASSIC_PATH,
                {
                    docs: docsOptions,
                    blog: false,
                    pages: false,
                    theme: { customCss: [customCssPath] },
                },
            ],
        ],
    };

    return {
        config: `// @generated by trickfire-docs — do not edit\nexport default ${JSON.stringify(cfg, null, 2)};\n`,
        sidebars,
    };
}
