import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ResolvedDocsConfig } from "./resolve.js";
import { convertSidebar } from "./sidebar.js";

// This module is bundled into dist-cli/cli.js; single-project.js lives in the same directory.
const SINGLE_PROJECT_CONFIG_PATH = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "single-project.js"
);

export interface GeneratedFiles {
    /** Content for .trickfire-docs/docusaurus.config.js */
    config: string;
    /** Content for .trickfire-docs/sidebars.js, or null to use autogenerated sidebar. */
    sidebars: string | null;
}

export function generateFiles(config: ResolvedDocsConfig, projectRoot: string): GeneratedFiles {
    const trickfireDir = path.resolve(projectRoot, ".trickfire-docs");
    const sidebarsPath = config.sidebar ? path.join(trickfireDir, "sidebars.js") : null;

    let sidebars: string | null = null;
    if (config.sidebar) {
        const converted = convertSidebar(config.sidebar);
        sidebars = `// @generated by trickfire-docs — do not edit\nexport default { sidebar: ${JSON.stringify(converted, null, 2)} };\n`;
    }

    const options = {
        projectRoot,
        sidebarsPath,
        name: config.name,
        description: config.description ?? "",
    };

    const configJs = [
        `// @generated by trickfire-docs — do not edit`,
        `import { createSingleProjectConfig } from ${JSON.stringify(SINGLE_PROJECT_CONFIG_PATH)};`,
        `export default createSingleProjectConfig(${JSON.stringify(options, null, 2)});`,
    ].join("\n");

    return { config: configJs, sidebars };
}
