import { readdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Config } from "@docusaurus/types";
import type { Options as PresetOptions } from "@docusaurus/preset-classic";
import type { Options as DocsOptions } from "@docusaurus/plugin-content-docs";

const SITE_URL = "https://docs.trickfirerobotics.com";
const CONTENT_DIR = path.join(process.cwd(), "content");
const DEV_FIXTURES_DIR = path.join(process.cwd(), "dev-fixtures");
const IS_DEV = process.env.NODE_ENV !== "production";

// Sidebar types and conversion — mirrors framework/config/sidebar.ts
type SidebarLinkItem = { label: string; slug?: string; link?: string };
type SidebarGroup = { label: string; items: SidebarItem[]; collapsed?: boolean };
type SidebarItem = SidebarLinkItem | SidebarGroup;

type DocusaurusSidebarItem =
    | { type: "doc"; id: string; label: string }
    | { type: "link"; href: string; label: string }
    | { type: "category"; label: string; collapsed: boolean; items: DocusaurusSidebarItem[] };

function convertItem(item: SidebarItem): DocusaurusSidebarItem {
    if ("items" in item) {
        return {
            type: "category",
            label: item.label,
            collapsed: item.collapsed ?? false,
            items: item.items.map(convertItem),
        };
    }
    if (item.link) {
        return { type: "link", href: item.link, label: item.label };
    }
    return { type: "doc", id: item.slug ?? item.label, label: item.label };
}

function getFirstDocId(sidebar: SidebarItem[]): string | undefined {
    for (const item of sidebar) {
        if ("items" in item) {
            const first = getFirstDocId(item.items);
            if (first) return first;
        } else if (item.slug) {
            return item.slug;
        }
    }
    return undefined;
}

function makeRedirectHtml(url: string): string {
    return (
        `<!doctype html><html lang="en"><head><meta charset="UTF-8">` +
        `<title>Redirecting…</title>` +
        `<meta http-equiv="refresh" content="0; url=${url}">` +
        `<script>window.location.replace(${JSON.stringify(url)})</script></head>` +
        `<body><p>Redirecting to <a href="${url}">${url}</a>…</p></body></html>\n`
    );
}

interface RepoMeta {
    id: string;
    name: string;
    description: string;
    basePath: string;
    sidebarPath?: string;
    firstDocId?: string;
}

function getReposFromDir(baseDir: string): RepoMeta[] {
    if (!existsSync(baseDir)) return [];
    return readdirSync(baseDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
        .map((repo) => {
            const repoDir = path.join(baseDir, repo);
            try {
                const cfgPath = path.join(repoDir, "docs.config.json");
                const cfg = JSON.parse(readFileSync(cfgPath, "utf-8")) as {
                    name?: string;
                    description?: string;
                    sidebar?: SidebarItem[];
                };

                let sidebarPath: string | undefined;
                let firstDocId: string | undefined;
                if (cfg.sidebar) {
                    const converted = cfg.sidebar.map(convertItem);
                    const generatedPath = path.join(repoDir, "sidebars.generated.js");
                    writeFileSync(
                        generatedPath,
                        `// @generated by trickfire-docs — do not edit\nexport default { sidebar: ${JSON.stringify(converted, null, 2)} };\n`
                    );
                    sidebarPath = generatedPath;
                    firstDocId = getFirstDocId(cfg.sidebar);
                }

                return {
                    id: repo,
                    name: cfg.name ?? repo,
                    description: cfg.description ?? "",
                    basePath: repoDir,
                    sidebarPath,
                    firstDocId,
                };
            } catch {
                return { id: repo, name: repo, description: "", basePath: repoDir };
            }
        });
}

export default async function createConfig(): Promise<Config> {
    const repoMeta: RepoMeta[] = [
        ...getReposFromDir(CONTENT_DIR),
        ...(IS_DEV ? getReposFromDir(DEV_FIXTURES_DIR) : []),
    ];

    const frameworkDocsPlugin: NonNullable<Config["plugins"]>[number] = [
        "@docusaurus/plugin-content-docs",
        {
            id: "framework",
            path: "docs",
            routeBasePath: "trickfire-docs",
            sidebarPath: "./docs-sidebars.js",
        } satisfies DocsOptions,
    ];

    const docsPlugins: Config["plugins"] = repoMeta.map(({ id, basePath, sidebarPath }) => [
        "@docusaurus/plugin-content-docs",
        {
            id,
            path: basePath,
            routeBasePath: id,
            ...(sidebarPath && { sidebarPath }),
        } satisfies DocsOptions,
    ]);

    // Generates build/<id>/index.html redirect pages that Docusaurus doesn't
    // produce when there is no index.md. Falls back to the first directory in
    // the build output (= first alphabetical doc) when no sidebar is configured.
    const subprojectRedirectsPlugin: NonNullable<Config["plugins"]>[number] = () => ({
        name: "trickfire-subproject-redirects",
        postBuild({ outDir }: { outDir: string }) {
            for (const { id, firstDocId } of repoMeta) {
                const indexPath = path.join(outDir, id, "index.html");
                if (existsSync(indexPath)) continue;

                let target = firstDocId;
                if (!target) {
                    const repoOutDir = path.join(outDir, id);
                    if (!existsSync(repoOutDir)) continue;
                    target = readdirSync(repoOutDir, { withFileTypes: true })
                        .filter((d) => d.isDirectory())
                        .map((d) => d.name)
                        .sort()[0];
                }
                if (!target) continue;

                writeFileSync(indexPath, makeRedirectHtml(`/${id}/${target}/`));
            }
        },
    });

    const projectDropdownItems = repoMeta.map(({ id, name, firstDocId }) => ({
        label: name,
        to: firstDocId ? `/${id}/${firstDocId}/` : `/${id}/`,
    }));

    return {
        title: "TrickFire Robotics Docs",
        tagline: "Documentation for TrickFire Robotics projects",
        favicon: "favicon.ico",
        url: SITE_URL,
        baseUrl: "/",
        staticDirectories: ["public"],
        onBrokenLinks: "warn",
        onBrokenMarkdownLinks: "warn",
        customFields: {
            repoMeta: repoMeta.map(({ id, name, description, firstDocId }) => ({
                id,
                name,
                description,
                firstDocId,
            })),
            frameworkMeta: {
                name: "Docs Framework",
                routeBasePath: "trickfire-docs",
            },
        },
        future: {
            faster: {
                rspackBundler: true,
                rspackPersistentCache: true,
                swcJsLoader: true,
                swcJsMinimizer: true,
                swcHtmlMinimizer: true,
            },
        },
        themeConfig: {
            colorMode: {
                defaultMode: "dark",
                disableSwitch: true,
                respectPrefersColorScheme: false,
            },
            navbar: {
                title: "",
                logo: {
                    alt: "TrickFire Robotics logo",
                    src: "nav-logo.png",
                    srcDark: "nav-logo.png",
                    width: 80,
                    height: 30,
                },
                items: [
                    {
                        to: "/trickfire-docs/",
                        label: "Docs Framework",
                        position: "left" as const,
                    },
                    ...projectDropdownItems.map((item) => ({
                        ...item,
                        position: "left" as const,
                    })),
                    {
                        href: "https://trickfirerobotics.com",
                        position: "right" as const,
                        className: "navbar-icon-link navbar-website-link",
                        "aria-label": "Website",
                    },
                    {
                        href: "https://github.com/TrickfireRobotics",
                        position: "right" as const,
                        className: "navbar-icon-link navbar-github-link",
                        "aria-label": "GitHub",
                    },
                    {
                        href: "https://www.notion.so/trickfire/invite/7f153eec8ed8ebe4608dc95892fce859540f8640",
                        position: "right" as const,
                        className: "navbar-icon-link navbar-notion-link",
                        "aria-label": "Notion",
                    },
                ],
            },
        },
        presets: [
            [
                "classic",
                {
                    docs: false,
                    blog: false,
                    theme: { customCss: ["./src/css/custom.css"] },
                } satisfies PresetOptions,
            ],
        ],
        plugins: [frameworkDocsPlugin, ...docsPlugins, subprojectRedirectsPlugin],
    };
}
